categories = ["Added", "Changed", "Fixed", "Improved", "Removed"]
colored_output = true
enable_debug = true
enable_footers = true
excluded_commit_tags = []
show_commit_hash = false
show_prefix = false
sort_by = "name"
template_prefix = "JIRA-1234"
